### PR TITLE
Ran generate-test-vectors in tbdex-js PR #152 to update test vectors

### PR DESCRIPTION
**Pull request by jiyoontbd**

### CODE REVIEW

**Review by diehuxx — COMMENTED** [review]
Why are these vectors being updated? What is the purpose of the change?

**Comment by jiyoontbd** [comment]
> Why are these vectors being updated? What is the purpose of the change?

These vectors were updated due to `generate-test-vectors` file being updated in [this pr](https://github.com/TBD54566975/tbdex-js/pull/152/) - the PR changes included overwriting the files in the tbdex submodule, and also included adding of new generate methods for close, order, and orderstatus. i ran `pnpm generate-test-vector` in the tbdex-js/packages/protocol directory, which overwrote these files and i created a PR for these changes.

**Comment by diehuxx** [comment]
> @diehuxx of note there were also errors in the previous test vectors which were leading to failing tests, @jiyoontbd's updates resolve those 👍

@kirahsapong @jiyoontbd 
Were you able to tell what the errors in the previous tests were?

**Comment by mistermoe** [comment]
@diehuxx yep the signatures in the vectors on main are incorrect due to a bug that we fixed in the work @kirahsapong @jiyoontbd and i have done

**Review by mistermoe — APPROVED** [review]

**Pull request merged**
