### PR TITLE
add codeowners

### PR DESCRIPTION
**Pull request by jiyoontbd**

### CODE REVIEW

**Review by KendallWeihe — APPROVED** [review]
I'm cool with this but I want to recognize that tbdex spec changes are upstream of a lot. Every change here is leveraged to downstream impacts. We definitely have not been considerate of this to date (pointing the finger at myself), though in our defense we're trying to get to v1 which requires quick iteration. My hope is adding more CODEOWNERs will help us towards that.

I say all of this because, I think establishing governance around this repo post-v1 should be considered a high priority. 

@phoebe-lew @mistermoe any thoughts on this?

**Review by KendallWeihe — APPROVED** [review]
I'm cool with this but I want to recognize that tbdex spec changes are upstream of a lot. Every change here is leveraged to downstream impacts. We definitely have not been considerate of this to date (pointing the finger at myself), though in our defense we're trying to get to v1 which requires quick iteration. My hope is adding more CODEOWNERs will help us towards that.

I say all of this because, I think establishing governance around this repo post-v1 should be considered a high priority. 

@phoebe-lew @mistermoe any thoughts on this?

**Comment by KendallWeihe** [comment]
GitHub spazzed out and posted my review twice

**Review by diehuxx — APPROVED** [review]
the power is already going to my head

**Comment by phoebe-lew** [comment]
@KendallWeihe I don't understand your comment. What does adding an additional codeowner have to do with spec changes being upstream of a lot?

**Review by phoebe-lew — APPROVED** [review]

**Comment by KendallWeihe** [comment]
> What does adding additional codeowners have to do with spec changes being upstream of a lot?

It's all a matter of governance, so I'm not intending to impose my view as the consensus nor to aim to come to a consensus here, only to recognize it as it is, _governance_, and to highlight the conversation of governance as a priority (at least, it's a priority in my opinion). I suppose we'd have to first come to a consensus of what it means to be a CODEOWNER. Does that imply liability, responsibility, etc? I'm under the working assumption that to be a CODEOWNER is to be held accountable for changes made. So within the context of expanding the list of CODEOWNERS, I suppose it's a bit metaphorical to expanding the number of supreme court justices, or congressional representatives, pick your poison. Of  course, the number of CODEOWNERS has nothing to do with the matter that the spec is upstream, that changes here are leveraged changes because the spec is the "source of truth" (once again, what does that mean exactly?), but it does impact the means through which changes are made, regardless of who the CODEOWNERS are, the _number_ of CODEOWNERS is one determining factor for how changes are made.

**Comment by jiyoontbd** [comment]
> how many reviewers are required? I would think for the spec & api it should be at least 3...

@decentralgabe It's 2 right now, but open to discussion. Ticket here: https://github.com/TBD54566975/tbdex/issues/252

**Pull request merged**
